# Generated by Django 3.0.6 on 2020-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
